# Generated by Django 5.0.6 on 2025-04-02 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'ordering': ['username'], 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['username'], 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='company_interactions',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='interview_coordination',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='opening_deadlines',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='registration_tracking',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='skills',
        ),
        migrations.AddField(
            model_name='administrator',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
