# Generated by Django 4.2.11 on 2025-04-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_administrator_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'ordering': ['username'], 'verbose_name': 'Administrator', 'verbose_name_plural': 'Administrators'},
        ),
        migrations.AddField(
            model_name='student',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode')], default='light', max_length=10),
        ),
    ]
